version: '3.4'

services:
  yamz:
    image: yamz
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port undefined"]
    ports:
      - 5678:5678
    environment:
      - FLASK_APP=yamz.py
